### ISSUE TITLE
License is incorrect.

### ISSUE THREAD

**Issue by gregkh** [jarun/keysniffer#1]
Your comment and LICENSE file says GPLv3+ yet your kernel module is telling the kernel it is "GPLv2".  Code trumps comments so please fix the comments and LICENSE file to be correct.

**Comment by jarun** [comment]
Thank you!
Fixed at https://github.com/jarun/keysniffer/commit/f8687d5fbdb6002160ca0699f847c16b87fa28a2.

However, I have a question regarding the compatibility of GPL v3 in kernel modules. If I use:

<pre>MODULE_LICENSE("GPL v3");</pre>

I get the following error during compilation:

<pre>FATAL: modpost: GPL-incompatible module kisni.ko uses GPL-only symbol 'unregister_keyboard_notifier'</pre>

This is also the reason behind the earlier inconsistency. I assumed I can still have a GPL v3 project that produces a GPL v2 binary.

Why is the module detected as GPL-incompatible, though I am using GPL v3?

**Comment by gregkh** [comment]
GPLv3 is not compatible with GPLv2, sorry, you can not have GPLv3-only kernel modules, it's impossible.

**Comment by gregkh** [comment]
If you really want "or any later", then mark your module as "v2 or any later version", which will make it compatible with v3, if that even makes any sense (hint, for Linux kernel modules it makes no sense...)

**Comment by jarun** [comment]
Thank you very much for explaining!
