### ISSUE TITLE
centos 7 64 bit 

### ISSUE THREAD

**Issue by ecsuae** [jarun/keysniffer#11]
i am using centos 7 , 
uname -r
3.10.0-1062.7.1.el7.x86_64
i followed instructions and installation goes smooth but after module loaded no matter what i type the file  cat /sys/kernel/debug/kisni/keys is always blank , can you guide what is wrong?

**Comment by jarun** [comment]
Please debug yourself. I don't use CentOS. If you can figure please leave a note.

**Comment by jarun** [comment]
Maybe a security hardening is blocking it?

**Comment by jarun** [comment]
Closing as no response.
