### ISSUE TITLE
capture keypresses

### ISSUE THREAD

**Issue by piranna** [jarun/keysniffer#3]
Capture keypresses instead of characters for increased flexibility, like keys combinations or not be attached to US keyboard.

**Comment by jarun** [comment]
Would you mind adding a module param to achieve this and record the keypresses? I would be very happy to merge the PR.

**Comment by dvad924** [comment]
I think I have a working version of request.

https://github.com/dvad924/keysniffer

**Comment by jarun** [comment]
fixed at https://github.com/jarun/keysniffer/commit/6f94d108092e6b60b3be54d4fc8f7c52028cb4cc.
